version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"
    versioning-strategy: "increase-if-necessary"

  - package-ecosystem: "npm"
    directory: "/documentation/"
    schedule:
      interval: "weekly"
    target-branch: "main"
    versioning-strategy: "increase-if-necessary"

  - package-ecosystem: "npm"
    directory: "/components/"
    schedule:
      interval: "weekly"
    target-branch: "main"
    versioning-strategy: "increase-if-necessary"
