name: Continuous Delivery

on:
  push:
    branches:
      - main

jobs:
  continuous-delivery:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: install, build, lint and test
        run: |
          yarn
          yarn bootstrap
          yarn build
          yarn lint
          yarn test

      # - name: "TODO: Deploy to Github Pages and remove azure deploy below"
      #   uses: azure/webapps-deploy@v2
      #   with:
      #     app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
      #     slot-name: "production"
      #     publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
      #     package: .
